import type { AreaChartConfig, ComparisonItem } from '@/interfaces/chart-config.interface';

const economiaComparisonItems: ComparisonItem[] = [
  { keyword: 'inflação', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'desemprego', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'crescimento', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'custo de vida', geo: 'BR-RN', time: 'today 12-m' },
];

const economiaExploreQuery = 'geo=BR-RN&q=infla%C3%A7%C3%A3o,desemprego,crescimento,custo%20de%20vida&hl=pt&date=today 12-m,today 12-m,today 12-m,today 12-m';

const segurancaComparisonItems: ComparisonItem[] = [
  { keyword: 'Violência Urbana', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'criminalidade', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'drogas', geo: 'BR-RN', time: 'today 12-m' },
];

const segurancaExploreQuery = 'geo=BR-RN&q=Viol%C3%AAncia%20Urbana,criminalidade,drogas&hl=pt&date=today 12-m,today 12-m,today 12-m';

const saudeComparisonItems: ComparisonItem[] = [
  { keyword: 'Acesso', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'qualidade', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'custo de cuidados de saúde', geo: 'BR-RN', time: 'today 12-m' },
];

const saudeExploreQuery = 'geo=BR-RN&q=Acesso,qualidade,custo%20de%20cuidados%20de%20sa%C3%BAde&hl=pt&date=today 12-m,today 12-m,today 12-m';

const corrupcaoComparisonItems: ComparisonItem[] = [
  { keyword: 'Corrupção', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'confiança em líderes e instituições', geo: 'BR-RN', time: 'today 12-m' },
];

const corrupcaoExploreQuery = 'geo=BR-RN&q=Corrup%C3%A7%C3%A3o,confian%C3%A7a%20em%20l%C3%ADderes%20e%20institui%C3%A7%C3%B5es&hl=pt&date=today 12-m,today 12-m';

const servicosPublicosComparisonItems: ComparisonItem[] = [
  { keyword: 'Educação', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'Transporte', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'Moradia', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'Saneamento', geo: 'BR-RN', time: 'today 12-m' },
];

const servicosPublicosExploreQuery = 'geo=BR-RN&q=Educa%C3%A7%C3%A3o,Transporte,Moradia,Saneamento&hl=pt&date=today 12-m,today 12-m,today 12-m,today 12-m';

const meioAmbienteComparisonItems: ComparisonItem[] = [
  { keyword: 'poluição', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'aquecimento global', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'desastres naturais', geo: 'BR-RN', time: 'today 12-m' },
];

const meioAmbienteExploreQuery = 'geo=BR-RN&q=polui%C3%A7%C3%A3o,aquecimento%20global,desastres%20naturais&hl=pt&date=today 12-m,today 12-m,today 12-m';

const migracaoComparisonItems: ComparisonItem[] = [
  { keyword: 'Imigração', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'integração social', geo: 'BR-RN', time: 'today 12-m' },
  { keyword: 'desigualdade', geo: 'BR-RN', time: 'today 12-m' },
];

const migracaoExploreQuery = 'geo=BR-RN&q=Imigra%C3%A7%C3%A3o,integra%C3%A7%C3%A3o%20social,desigualdade&hl=pt&date=today 12-m,today 12-m,today 12-m';

const guestPath = 'https://trends.google.com.br:443/trends/embed/';

export const chartsConfig: Record<string, AreaChartConfig> = {
  // Economia - ID: 1
  '1': {
    areaId: '1',
    areaName: 'Economia',
    description: 'Inflação, desemprego, crescimento e custo de vida',
    widgets: [
      {
        type: 'TIMESERIES',
        title: 'Interesse ao longo do tempo',
        comparisonItem: economiaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: economiaExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP',
        title: 'Detalhamento comparado por cidade',
        comparisonItem: economiaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: economiaExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_0',
        title: 'Interesses por cidade',
        subtitle: 'Inflação',
        comparisonItem: economiaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: economiaExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_0',
        title: 'Pesquisas relacionadas',
        subtitle: 'Inflação',
        comparisonItem: economiaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: economiaExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_1',
        title: 'Interesses por cidade',
        subtitle: 'Desemprego',
        comparisonItem: economiaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: economiaExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_1',
        title: 'Pesquisas relacionadas',
        subtitle: 'Desemprego',
        comparisonItem: economiaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: economiaExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_2',
        title: 'Interesses por cidade',
        subtitle: 'Crescimento',
        comparisonItem: economiaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: economiaExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_2',
        title: 'Pesquisas relacionadas',
        subtitle: 'Crescimento',
        comparisonItem: economiaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: economiaExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_3',
        title: 'Interesses por cidade',
        subtitle: 'Custo de vida',
        comparisonItem: economiaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: economiaExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_3',
        title: 'Pesquisas relacionadas',
        subtitle: 'Custo de vida',
        comparisonItem: economiaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: economiaExploreQuery,
        guestPath,
      },
    ],
  },
  // Segurança e Crime - ID: 2
  '2': {
    areaId: '2',
    areaName: 'Segurança e Crime',
    description: 'Violência Urbana, criminalidade e drogas',
    widgets: [
      {
        type: 'TIMESERIES',
        title: 'Interesse ao longo do tempo',
        comparisonItem: segurancaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: segurancaExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP',
        title: 'Detalhamento comparado por cidade',
        comparisonItem: segurancaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: segurancaExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_0',
        title: 'Interesses por cidade',
        subtitle: 'Violência Urbana',
        comparisonItem: segurancaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: segurancaExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_0',
        title: 'Pesquisas relacionadas',
        subtitle: 'Violência Urbana',
        comparisonItem: segurancaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: segurancaExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_1',
        title: 'Interesses por cidade',
        subtitle: 'Criminalidade',
        comparisonItem: segurancaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: segurancaExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_1',
        title: 'Pesquisas relacionadas',
        subtitle: 'Criminalidade',
        comparisonItem: segurancaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: segurancaExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_2',
        title: 'Interesses por cidade',
        subtitle: 'Drogas',
        comparisonItem: segurancaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: segurancaExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_2',
        title: 'Pesquisas relacionadas',
        subtitle: 'Drogas',
        comparisonItem: segurancaComparisonItems,
        category: 0,
        property: '',
        exploreQuery: segurancaExploreQuery,
        guestPath,
      },
    ],
  },
  // Saúde - ID: 3
  '3': {
    areaId: '3',
    areaName: 'Saúde',
    description: 'Acesso, qualidade, custo de cuidados de saúde',
    widgets: [
      {
        type: 'TIMESERIES',
        title: 'Interesse ao longo do tempo',
        comparisonItem: saudeComparisonItems,
        category: 0,
        property: '',
        exploreQuery: saudeExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP',
        title: 'Detalhamento comparado por cidade',
        comparisonItem: saudeComparisonItems,
        category: 0,
        property: '',
        exploreQuery: saudeExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_0',
        title: 'Interesses por cidade',
        subtitle: 'Acesso',
        comparisonItem: saudeComparisonItems,
        category: 0,
        property: '',
        exploreQuery: saudeExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_0',
        title: 'Pesquisas relacionadas',
        subtitle: 'Acesso',
        comparisonItem: saudeComparisonItems,
        category: 0,
        property: '',
        exploreQuery: saudeExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_1',
        title: 'Interesses por cidade',
        subtitle: 'Qualidade',
        comparisonItem: saudeComparisonItems,
        category: 0,
        property: '',
        exploreQuery: saudeExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_1',
        title: 'Pesquisas relacionadas',
        subtitle: 'Qualidade',
        comparisonItem: saudeComparisonItems,
        category: 0,
        property: '',
        exploreQuery: saudeExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_2',
        title: 'Interesses por cidade',
        subtitle: 'Custo de cuidados de saúde',
        comparisonItem: saudeComparisonItems,
        category: 0,
        property: '',
        exploreQuery: saudeExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_2',
        title: 'Pesquisas relacionadas',
        subtitle: 'Custo de cuidados de saúde',
        comparisonItem: saudeComparisonItems,
        category: 0,
        property: '',
        exploreQuery: saudeExploreQuery,
        guestPath,
      },
    ],
  },
  // Corrupção e política - ID: 4
  '4': {
    areaId: '4',
    areaName: 'Corrupção e política',
    description: 'Corrupção, confiança em líderes e instituições',
    widgets: [
      {
        type: 'TIMESERIES',
        title: 'Interesse ao longo do tempo',
        comparisonItem: corrupcaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: corrupcaoExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP',
        title: 'Detalhamento comparado por cidade',
        comparisonItem: corrupcaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: corrupcaoExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_0',
        title: 'Interesses por cidade',
        subtitle: 'Corrupção',
        comparisonItem: corrupcaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: corrupcaoExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_0',
        title: 'Pesquisas relacionadas',
        subtitle: 'Corrupção',
        comparisonItem: corrupcaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: corrupcaoExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_1',
        title: 'Interesses por cidade',
        subtitle: 'Confiança em líderes e instituições',
        comparisonItem: corrupcaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: corrupcaoExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_1',
        title: 'Pesquisas relacionadas',
        subtitle: 'Confiança em líderes e instituições',
        comparisonItem: corrupcaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: corrupcaoExploreQuery,
        guestPath,
      },
    ],
  },
  // Serviços públicos sociais - ID: 5
  '5': {
    areaId: '5',
    areaName: 'Serviços públicos sociais',
    description: 'Educação, transporte, moradia e saneamento',
    widgets: [
      {
        type: 'TIMESERIES',
        title: 'Interesse ao longo do tempo',
        comparisonItem: servicosPublicosComparisonItems,
        category: 0,
        property: '',
        exploreQuery: servicosPublicosExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP',
        title: 'Detalhamento comparado por cidade',
        comparisonItem: servicosPublicosComparisonItems,
        category: 0,
        property: '',
        exploreQuery: servicosPublicosExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_0',
        title: 'Interesses por cidade',
        subtitle: 'Educação',
        comparisonItem: servicosPublicosComparisonItems,
        category: 0,
        property: '',
        exploreQuery: servicosPublicosExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_0',
        title: 'Pesquisas relacionadas',
        subtitle: 'Educação',
        comparisonItem: servicosPublicosComparisonItems,
        category: 0,
        property: '',
        exploreQuery: servicosPublicosExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_1',
        title: 'Interesses por cidade',
        subtitle: 'Transporte',
        comparisonItem: servicosPublicosComparisonItems,
        category: 0,
        property: '',
        exploreQuery: servicosPublicosExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_1',
        title: 'Pesquisas relacionadas',
        subtitle: 'Transporte',
        comparisonItem: servicosPublicosComparisonItems,
        category: 0,
        property: '',
        exploreQuery: servicosPublicosExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_2',
        title: 'Interesses por cidade',
        subtitle: 'Moradia',
        comparisonItem: servicosPublicosComparisonItems,
        category: 0,
        property: '',
        exploreQuery: servicosPublicosExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_2',
        title: 'Pesquisas relacionadas',
        subtitle: 'Moradia',
        comparisonItem: servicosPublicosComparisonItems,
        category: 0,
        property: '',
        exploreQuery: servicosPublicosExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_3',
        title: 'Interesses por cidade',
        subtitle: 'Saneamento',
        comparisonItem: servicosPublicosComparisonItems,
        category: 0,
        property: '',
        exploreQuery: servicosPublicosExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_3',
        title: 'Pesquisas relacionadas',
        subtitle: 'Saneamento',
        comparisonItem: servicosPublicosComparisonItems,
        category: 0,
        property: '',
        exploreQuery: servicosPublicosExploreQuery,
        guestPath,
      },
    ],
  },
  // Meio ambiente e clima - ID: 6
  '6': {
    areaId: '6',
    areaName: 'Meio ambiente e clima',
    description: 'Poluição, aquecimento global, desastres naturais',
    widgets: [
      {
        type: 'TIMESERIES',
        title: 'Interesse ao longo do tempo',
        comparisonItem: meioAmbienteComparisonItems,
        category: 0,
        property: '',
        exploreQuery: meioAmbienteExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP',
        title: 'Detalhamento comparado por cidade',
        comparisonItem: meioAmbienteComparisonItems,
        category: 0,
        property: '',
        exploreQuery: meioAmbienteExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_0',
        title: 'Interesses por cidade',
        subtitle: 'Poluição',
        comparisonItem: meioAmbienteComparisonItems,
        category: 0,
        property: '',
        exploreQuery: meioAmbienteExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_0',
        title: 'Pesquisas relacionadas',
        subtitle: 'Poluição',
        comparisonItem: meioAmbienteComparisonItems,
        category: 0,
        property: '',
        exploreQuery: meioAmbienteExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_1',
        title: 'Interesses por cidade',
        subtitle: 'Aquecimento global',
        comparisonItem: meioAmbienteComparisonItems,
        category: 0,
        property: '',
        exploreQuery: meioAmbienteExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_1',
        title: 'Pesquisas relacionadas',
        subtitle: 'Aquecimento global',
        comparisonItem: meioAmbienteComparisonItems,
        category: 0,
        property: '',
        exploreQuery: meioAmbienteExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_2',
        title: 'Interesses por cidade',
        subtitle: 'Desastres naturais',
        comparisonItem: meioAmbienteComparisonItems,
        category: 0,
        property: '',
        exploreQuery: meioAmbienteExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_2',
        title: 'Pesquisas relacionadas',
        subtitle: 'Desastres naturais',
        comparisonItem: meioAmbienteComparisonItems,
        category: 0,
        property: '',
        exploreQuery: meioAmbienteExploreQuery,
        guestPath,
      },
    ],
  },
  // Migração e sociedade - ID: 7
  '7': {
    areaId: '7',
    areaName: 'Migração e sociedade',
    description: 'Imigração, integração social, desigualdade',
    widgets: [
      {
        type: 'TIMESERIES',
        title: 'Interesse ao longo do tempo',
        comparisonItem: migracaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: migracaoExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP',
        title: 'Detalhamento comparado por cidade',
        comparisonItem: migracaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: migracaoExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_0',
        title: 'Interesses por cidade',
        subtitle: 'Imigração',
        comparisonItem: migracaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: migracaoExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_0',
        title: 'Pesquisas relacionadas',
        subtitle: 'Imigração',
        comparisonItem: migracaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: migracaoExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_1',
        title: 'Interesses por cidade',
        subtitle: 'Integração social',
        comparisonItem: migracaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: migracaoExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_1',
        title: 'Pesquisas relacionadas',
        subtitle: 'Integração social',
        comparisonItem: migracaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: migracaoExploreQuery,
        guestPath,
      },
      {
        type: 'GEO_MAP_2',
        title: 'Interesses por cidade',
        subtitle: 'Desigualdade',
        comparisonItem: migracaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: migracaoExploreQuery,
        guestPath,
      },
      {
        type: 'RELATED_QUERIES_2',
        title: 'Pesquisas relacionadas',
        subtitle: 'Desigualdade',
        comparisonItem: migracaoComparisonItems,
        category: 0,
        property: '',
        exploreQuery: migracaoExploreQuery,
        guestPath,
      },
    ],
  },
};

